# Trefferliste vierte Zeile
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      cells['department'].value,
      v,
      v,
      ''
    )
    + forNonBlank(
      cells['title'].value,
      v,
      ' [' + v + ']',
      ''
    )
  newColumnName: displayAddition2
  columnInsertIndex: 1
