# Trefferliste vierte Zeile
# Jahresangabe wird bei Personen extrahiert mit RegEx positive lookahead, weil auch Angaben v. Chr. (-0123) erlaubt sind
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forNonBlank(
        cells['dateActivityStart'].value,
        v,
        v.split(/(?=-)/)[0],
        ''
      )
      +
      if(
        or(
          isNonBlank(cells['dateActivityStart'].value),
          isNonBlank(cells['dateActivityEnd'].value)
        ),
        '-',
        ''
      )
      +
      forNonBlank(
        cells['dateActivityEnd'].value,
        v,
        v.split(/(?=-)/)[0],
        ''
      ),
      x,
      'Wirkungsdaten: ' + x,
      null
    )
  newColumnName: displayAddition2
  columnInsertIndex: 1