image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - name: install go-task, OpenRefine and openrefine-client
    init: |
      sh -c \"$(curl --location https://taskfile.dev/install.sh)\" -- -d -b ~/.local/bin
      task install

# Ports to expose on workspace startup
ports:
  - port: 3333
    onOpen: notify
    name: OpenRefine
