image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - name: install go-task, OpenRefine and openrefine-client
    init: |
      sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/.local/bin/yq && chmod +x ~/.local/bin/yq
      sudo apt-get update && sudo apt-get install -y bc
      task install

# Ports to expose on workspace startup
ports:
  - port: 3333
    onOpen: notify
    name: OpenRefine
