# https://taskfile.dev

version: '3'

vars:
  DIR: '{{default "example" .DIR}}'
  MEMORY: '{{default "2G" .MEMORY}}'
  PORT: '{{default "3333" .PORT}}'

tasks:
  default:
    cmds:
      - task: main
    
  main:
    desc: Internformat aufbereiten für Online-Katalog
    cmds:
      - |
        # Zeitstempel zu Beginn
        mkdir -p .task/timer; date -u +%s.%N > ".task/timer/{{.TASK}}"
      - |
        # Arbeitsverzeichnis leeren
        rm -r "{{.DIR}}/tmp" 2> /dev/null || true; mkdir -p "{{.DIR}}/tmp"
      - |
        # Konfigurationsdateien ins Arbeitsverzeichnis kopieren
        cp -r "config" "{{.DIR}}/tmp/"
      - |
        # orcli das script main.sh ausführen lassen
        DIR={{.DIR}} openrefine/orcli run "scripts/main.sh" --memory "{{.MEMORY}}" --port "{{.PORT}}"
      - |
        # Kopie der Konfigurationsdateien im Arbeitsverzeichnis löschen
        rm -r "{{.DIR}}/tmp/config" 2> /dev/null || true
      - |
        # Änderungsstatistik mit git diff
        git --no-pager diff --stat --no-index {{.DIR}}/output {{.DIR}}/tmp 2> /dev/null || true
      - |
        # Vorheriges Ergebnis überschreiben
        rm -r "{{.DIR}}/output" 2> /dev/null || true; mv "{{.DIR}}/tmp" "{{.DIR}}/output"
      - |
        # Laufzeit berechnen
        >&2 echo "{{.TASK}} run time: $(bc <<<"$(date -u +%s.%N)-$(cat ".task/timer/{{.TASK}}")") seconds"
    sources:
      - '{{.DIR}}/input/**'
      - scripts/main.sh
      - 'config/*.*'
      - 'config/main/**'
    generates:
      - '{{.DIR}}/output/**'
    preconditions:
      - sh: test -f openrefine/orcli
        msg: "orcli not found; try task install"
      - sh: test -f openrefine/refine
        msg: "OpenRefine not found; try task install"
      - command -v jq
      - command -v curl
      - command -v java
      - test -d {{.DIR}}

  dev:
    desc: Entwicklungsmodus (interaktiv)
    cmds:
      - |
        # Arbeitsverzeichnis leeren
        rm -r "{{.DIR}}/tmp" 2> /dev/null || true; mkdir -p "{{.DIR}}/tmp"
      - |
        # Konfigurationsdateien ins Arbeitsverzeichnis kopieren
        cp -r "config" "{{.DIR}}/tmp/"
      - |
        # orcli das script main.sh im interaktiven Modus ausführen lassen
        DIR={{.DIR}} openrefine/orcli run "scripts/main.sh" --memory "{{.MEMORY}}" --port "{{.PORT}}" --interactive
      - |
        # Arbeitsverzeichnis löschen
        rm -r "{{.DIR}}/tmp" 2> /dev/null || true
    preconditions:
      - sh: test -f openrefine/orcli
        msg: "orcli not found; try task install"
      - sh: test -f openrefine/refine
        msg: "OpenRefine not found; try task install"
      - command -v jq
      - command -v curl
      - command -v java
      - test -d {{.DIR}}

  install:
    desc: install requirements into subdirectories
    cmds:
      - task: install_openrefine
      - task: install_orcli

  install_openrefine:
    internal: true
    cmds:
      - mkdir -p openrefine
      - wget --no-verbose -O openrefine.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/3.7.6/openrefine-linux-3.7.6.tar.gz
      - tar -xzf openrefine.tar.gz -C openrefine --strip 1 && rm openrefine.tar.gz
      - rm openrefine/refine.ini
       
  install_orcli:
    internal: true
    cmds:
      - mkdir -p openrefine
      - wget --no-verbose -O openrefine/orcli https://github.com/opencultureconsulting/orcli/releases/download/v0.2.1/orcli
      - chmod +x openrefine/orcli
