# https://taskfile.dev

version: '3'

vars:
  DIR: '{{default "example" .DIR}}'
  MEMORY: '{{default "2G" .MEMORY}}'
  PORT: '{{default "3333" .PORT}}'

tasks:
  default:
    cmds:
      - task: main
    
  main:
    desc: Internformat aufbereiten für Online-Katalog
    cmds:
      - |
        # Zeitstempel zu Beginn
        mkdir -p .task/timer; date -u +%s.%N > ".task/timer/{{.TASK}}"
      - |
        # Arbeitsverzeichnis leeren
        rm -r "{{.DIR}}/tmp" 2> /dev/null || true; mkdir -p "{{.DIR}}/tmp"
      - |
        # Konfigurationsdateien ins Arbeitsverzeichnis kopieren
        cp -r "config" "{{.DIR}}/tmp/"
      - |
        # orcli das script main.sh ausführen lassen
        DIR={{.DIR}} openrefine/orcli run "scripts/main.sh" --memory "{{.MEMORY}}" --port "{{.PORT}}"
      - |
        # Kopie der Konfigurationsdateien im Arbeitsverzeichnis löschen
        rm -r "{{.DIR}}/tmp/config" 2> /dev/null || true
      - |
        # Vorheriges Ergebnis überschreiben
        rm -r "{{.DIR}}/output" 2> /dev/null || true; mv "{{.DIR}}/tmp" "{{.DIR}}/output"
      - |
        # Laufzeit berechnen
        >&2 echo "{{.TASK}} run time: $(bc <<<"$(date -u +%s.%N)-$(cat ".task/timer/{{.TASK}}")") seconds"
    sources:
      - '{{.DIR}}/input/**'
      - scripts/main.sh
      - 'config/*.*'
      - 'config/main/**/**'
    generates:
      - '{{.DIR}}/output/**'
    preconditions:
      - sh: test -f openrefine/orcli
        msg: "orcli not found; try task install"
      - sh: test -f openrefine/refine
        msg: "OpenRefine not found; try task install"
      - command -v jq
      - command -v curl
      - command -v java
      - test -d {{.DIR}}

  dev:
    desc: Entwicklungsmodus (interaktiv)
    cmds:
      - |
        # Arbeitsverzeichnis leeren
        rm -r "{{.DIR}}/tmp" 2> /dev/null || true; mkdir -p "{{.DIR}}/tmp"
      - |
        # Konfigurationsdateien ins Arbeitsverzeichnis kopieren
        cp -r "config" "{{.DIR}}/tmp/"
      - |
        # orcli das script main.sh im interaktiven Modus ausführen lassen
        DIR={{.DIR}} openrefine/orcli run "scripts/main.sh" --memory "{{.MEMORY}}" --port "{{.PORT}}" --interactive
      - |
        # Arbeitsverzeichnis löschen
        rm -r "{{.DIR}}/tmp" 2> /dev/null || true
    preconditions:
      - sh: test -f openrefine/orcli
        msg: "orcli not found; try task install"
      - sh: test -f openrefine/refine
        msg: "OpenRefine not found; try task install"
      - command -v jq
      - command -v curl
      - command -v java
      - test -d {{.DIR}}

  solr:
    desc: Indexierung in Solr testen
    cmds:
      - solr/bin/solr delete -c dla &> /dev/null || true
      - solr/bin/solr stop &> /dev/null || true
      - rm -r "solr/server/solr/dla" 2> /dev/null || true; mkdir -p "solr/server/solr/dla"
      - cp config/solr/* solr/server/solr/dla/
      - touch solr/server/solr/dla/core.properties solr/server/solr/dla/stopwords.txt solr/server/solr/dla/synonyms.txt
      - solr/bin/solr start -a "-XX:+IgnoreUnrecognizedVMOptions" && sleep 1
      - solr/bin/post -c dla example/output/*.jsonl

  install:
    desc: install requirements into subdirectories
    cmds:
      - task: install_openrefine
      - task: install_orcli
      - task: install_solr

  install_openrefine:
    internal: true
    cmds:
      - mkdir -p openrefine
      - wget --no-verbose -O openrefine.tar.gz https://github.com/OpenRefine/OpenRefine/releases/download/3.7.6/openrefine-linux-3.7.6.tar.gz
      - tar -xzf openrefine.tar.gz -C openrefine --strip 1 && rm openrefine.tar.gz
      - rm openrefine/refine.ini
       
  install_orcli:
    internal: true
    cmds:
      - mkdir -p openrefine
      - wget --no-verbose -O openrefine/orcli https://github.com/opencultureconsulting/orcli/releases/download/v0.2.2/orcli
      - chmod +x openrefine/orcli

  install_solr:
    internal: true
    cmds:
      - mkdir -p solr
      - wget --no-verbose -O solr.tgz https://archive.apache.org/dist/lucene/solr/7.7.3/solr-7.7.3.tgz
      - tar -xzf solr.tgz -C solr --strip 1 && rm solr.tgz
