- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: accession_id
  expression: |
    grel:
    forNonBlank(
      value.cross('be','id')[0].cells['accessionNumber'].value,
      x,
      x,
      null
    )
  newColumnName: accessionNumber
  columnInsertIndex: 2