# Nicht aufgelöste Codes entfernen (weniger als drei Zeichen)
- op: core/text-transform
  engineConfig:
    facets: []
  columnName: categoryMedia_mv
  expression: |
    grel:
    forNonBlank(
      filter(
        value.split('␟'),
        v,
        or(
          v.length() > 2,
          isNonBlank(v.find(/\p{Lu}\p{Lu}/).join(''))
        )
      ).join('␟'),
      x,
      x,
      null
    )
