# Anreicherung zusätzlicher Werte aus SY:subjectOther_mv via classification_id_mv -> SE:classificationSubject_id_mv
# vorhandene Werte in classificationSubjectOther_mv bleiben erhalten
- op: core/text-transform
  engineConfig:
    facets:
    facets: []
    mode: row-based
  columnName: classificationSubjectOther_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        cells['classification_id_mv'].value.split('␟'),
        classification,
        forNonBlank(
          classification.cross('se','id')[0].cells['classificationSubject_id_mv'].value,
          classificationSubjects,
          forEach(
            classificationSubjects.split('␟'),
            classificationSubject,
            forNonBlank(
              classificationSubject.cross('sy','id')[0].cells['subjectOther_mv'].value,
              v,
              v,
              null
            )
          ).join('␟'),
          null
        )
      ).join('␟'),
      x,
      forNonBlank(value, v, v, '') + '␟' + x,
      forNonBlank(value, v, v, null)
    )
