- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: parent_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('ak','id')[0].cells['titleResponsability'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: parent_titleResponsability_mv
  columnInsertIndex: 2
  