# Konvertierung in Boolean
- op: core/text-transform
  engineConfig:
    facets: []
  columnName: provenance
  expression: |
    grel:
    forNonBlank(
      value,
      v,
      v == 'True',
      null
    )
