# zugeordnete Materialien aus BI und HS über Exemplarsätze
# Cross-Zielfelder BI item_id_mv und HS item_id_mv sind in der Praxis nicht mehrfachbelegt
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forNonBlank(
        cells['item_id_mv'].value,
        items,
        forNonBlank(
          forEach(
            items.split('␟'),
            item,
            forNonBlank(
              [
                forNonBlank(
                  forEach(
                    item.cross('bi', 'item_id_mv'),
                    r,
                    forNonBlank(
                      r.cells['id'].value,
                      v,
                      v,
                      null
                    )
                  ).join('␝'),
                  x,
                  x,
                  null
                ),
                forNonBlank(
                  forEach(
                    item.cross('hs', 'item_id_mv'),
                    r,
                    forNonBlank(
                      r.cells['id'].value,
                      v,
                      v,
                      null
                    )
                  ).join('␝'),
                  x,
                  x,
                  null
                )
              ].join('␝'),
              x,
              x,
              '␣'
            )
          ).join('␟'),
          y,
          y,
          null
        ),
        null
      ),
      z,
      if(
        isNonBlank(z.replace(/␟|␣/,'')),
        z,
        null
      ),
      null
    )
  newColumnName: item_supplements_id_mv
  columnInsertIndex: 2
