# zugeordnete Materialien aus BI
# Cross-Zielfeld BI library_id_mv ist in der Praxis nicht mehrfachbelegt
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('bi', 'library_id_mv'),
        r,
        forNonBlank(
          r.cells['id'].value,
          v,
          v,
          null
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: supplements_id_mv
  columnInsertIndex: 2
