# Gewichtung Relevanzranking
- op: core/column-addition
  engineConfig:
    facets: []
  baseColumnName: id
  expression: |
    grel:
    with(
      forNonBlank(
        cells['id'].value.cross('au','collection_id_mv').length(),
        v,
        v,
        0
      )
      + forNonBlank(
        cells['id'].value.cross('bi','collection_id_mv').length(),
        v,
        v,
        0
      )
      + forNonBlank(
        cells['id'].value.cross('hs','collection_id_mv').length(),
        v,
        v,
        0
      ),
      x,
      if(
        x > 50,
        log(x) / 10 + 1.0,
        1.0
      )
    )
  newColumnName: searchBoost
  columnInsertIndex: 2
# Rundung auf 2 Nachkommastellen
- op: core/text-transform
  engineConfig:
    facets: []
  columnName: searchBoost
  expression: |
    grel:
    value.toString('%.2f').toNumber()
