# Facette Zeit
# Zeitspannen aus filterDateRange_mv umwandeln in ISO-8601 Zeitpunkte und validieren
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        cells['filterDateRange_mv'].value.split('␟'),
        v,
        with(
          v.replace('[','').replace(']','').replace(' ','').replace('TO','␟'),
          v,
          forEach(
            v.split('␟'),
            y,
            if(
              y.length() == 4,
              y + '-01-01T00:00:00Z',
              if(
                y.length() == 7,
                y + '-01T00:00:00Z',
                if(
                  y.length() == 10,
                  y + 'T00:00:00Z',
                  null
                )
              )
            )
          ).join('␟')
        )
      ).join('␟'),
      z,
      forEach(
        z.split('␟').uniques(),
        v,
        forNonBlank(
          v.toDate("yyyy-MM-dd'T'HH:mm:ssZ"),
          x,
          v,
          null
        )
      ).sort().join('␟'),
      null
    )
  newColumnName: filterDatePoint_mv
  columnInsertIndex: 2
