# In MM generierte Felder anreichern
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['accessLevel'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_accessLevel_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['fileExtension'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_fileExtension_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['hyperlink'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_hyperlink_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['license'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_license_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['rightsHolder'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_rightsHolder_mv
  columnInsertIndex: 2
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: digitalObject_id_mv
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          v.cross('mm','id')[0].cells['thumbnail'].value,
          x,
          x,
          '␣')
      ).join('␟'),
      x,
      if(
        isNonBlank(x.replace(/␟|␣/,'')),
        x,
        null
      ),
      null
    )
  newColumnName: digitalObject_thumbnail_mv
  columnInsertIndex: 2
