# Für den Export in Literaturverwaltungsprogramme wird ein RIS-Datensatz generiert.
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    'TY  - ' + 'GEN' + '\n'
    + forNonBlank(cells['id'].value, v, 'ID  - ' + v + '\n', '')
    + forNonBlank(cells['display'].value, v, 'TI  - ' + v + '\n', '')
    + 'ER  -'
  newColumnName: exportRIS
  columnInsertIndex: 2 # hinter id und display