# Facette Sammlung
# Über Verknüpfung (holding_id_mv) den Bestandstitel (BF:title) ermitteln
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: holding_id_mv
  expression: |-
    grel:
    forNonBlank(
      value,
      v,
      v.cross('bf','id')[0].cells['title'].value,
      null
    )
  newColumnName: filterCollection_mv
  columnInsertIndex: 2
