# Facette Personen und Körperschaften
# personAbout, corporationAbout:  "Über"
# personAt, corporationAt: "Unter"
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          cells['personAbout_display_mv'].value,
          v,
          forEach(
            v.split('␟'),
            x,
            x + '␝' + 'Über'
          ).join('␟'),
          null
        ),
        forNonBlank(
          cells['corporationAbout_display_mv'].value,
          v,
          forEach(
            v.split('␟'),
            x,
            x + '␝' + 'Über'
          ).join('␟'),
          null
        ),
        forNonBlank(
          cells['personAt_display_mv'].value,
          v,
          forEach(
            v.split('␟'),
            x,
            x + '␝' + 'Unter'
          ).join('␟'),
          null
        ),
        forNonBlank(
          cells['corporationAt_display_mv'].value,
          v,
          forEach(
            v.split('␟'),
            x,
            x + '␝' + 'Unter'
          ).join('␟'),
          null
        )
      ].join('␟'),
      z,
      filter(
        z.split('␟'),
        f,
        f[0] != '␣'
      ).uniques().join('␟'),
      null
    )
  newColumnName: filterAuthorityRelation_mv
  columnInsertIndex: 2
