# Personen und Körperschaften mit Trennzeichen ;
# Rolle (VON oder AN) abhängig von category, bei Briefwechseln VON + AN
# Manuskripte
- op: core/column-addition
  engineConfig:
    facets:
    - type: list
      expression: value
      columnName: category
      invert: false
      selection:
        - v:
            v: Manuskripte
        - v:
            v: Manuskripte anderer
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          cells['personBy_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['personBy_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        ),
        forNonBlank(
          cells['corporationBy_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['corporationBy_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        )
      ].join('; '),
      z,
      z,
      null
    )
  newColumnName: displayName
  columnInsertIndex: 1
# Briefe
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: value
      columnName: category
      invert: false
      selection:
        - v:
            v: Briefe anderer
        - v:
            v: Briefe von
        - v:
            v: Briefe an
    mode: row-based
  columnName: displayName
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          cells['personBy_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['personBy_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        ),
        forNonBlank(
          cells['corporationBy_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['corporationBy_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        ),
        forNonBlank(
          cells['personTo_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['personTo_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        ),
        forNonBlank(
          cells['corporationTo_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['corporationTo_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        )
      ].join('; '),
      z,
      z,
      null
    )
# Briefwechsel
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: value
      columnName: category
      invert: false
      selection:
        - v:
            v: Briefwechsel
        - v:
            v: Briefwechsel ohne Bestandsbildner
    mode: row-based
  columnName: displayName
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          cells['personBy_display_mv'].value,
          x,
          with(
            forEachIndex(
              x.split('␟'),
              i,
              v,
              if(
                not(
                  or(
                    v=='␣',
                    isBlank(v)
                  )
                ),
                forNonBlank(
                  cells['personBy_role_mv'].value.split('␟')[i].replace('␣',''),
                  role,
                  v + ' ' + role,
                  v
                ),
                null
              )
            ),
            y,
            if(
              y.length() > 1,
              y[0,2].join('; '),
              y[0]
            )
          ),
          null
        ),
        forNonBlank(
          cells['corporationBy_display_mv'].value,
          x,
          with(
            forEachIndex(
              x.split('␟'),
              i,
              v,
              if(
                not(
                  or(
                    v=='␣',
                    isBlank(v)
                  )
                ),
                forNonBlank(
                  cells['corporationBy_role_mv'].value.split('␟')[i].replace('␣',''),
                  role,
                  v + ' ' + role,
                  v
                ),
                null
              )
            ),
            y,
            if(
              y.length() > 1,
              y[0,2].join('; '),
              y[0]
            )
          ),
          null
        )
      ].join('; '),
      z,
      z,
      null
    )
# Dokumente
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: value
      columnName: category
      invert: false
      selection:
        - v:
            v: Manuskripte
        - v:
            v: Manuskripte anderer
    mode: row-based
  columnName: displayName
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          cells['personAbout_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['personAbout_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        ),
        forNonBlank(
          cells['corporationAbout_display_mv'].value,
          x,
          forEachIndex(
            x.split('␟'),
            i,
            v,
            if(
              not(
                or(
                  v=='␣',
                  isBlank(v)
                )
              ),
              forNonBlank(
                cells['corporationAbout_role_mv'].value.split('␟')[i].replace('␣',''),
                role,
                v + ' ' + role,
                v
              ),
              null
            )
          )[0],
          null
        )
      ].join('; '),
      z,
      z,
      null
    )
