# Verknüpfte Bestandstitel ermittelt über zugehörige Exemplare
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.cross('au','manifestation_id'),
        r,
        forNonBlank(
          r.cells['holding_display_mv'].value,
          x,
          x.replace('␟','␝'),
          '␣'
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: item_holding_display_mv
  columnInsertIndex: 2
