# Kürzel für Datenbestand
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel: 'AK'
  newColumnName: source
  columnInsertIndex: 1 # hinter Spalte id
