# Digitales Objekt aus Exemplarebene auf Titelebene kopieren (wenn Titelebene leer)
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_accessLevel_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_accessLevel_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_display_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_display_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]    
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_fileExtension_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_fileExtension_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_hyperlink_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_hyperlink_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_license_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_license_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_licenseNote_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_licenseNote_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_thumbnail_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_thumbnail_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
- op: core/text-transform
  engineConfig:
    facets:
    - type: list
      expression: isBlank(value)
      columnName: digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: true
    - type: list
      expression: isBlank(value)
      columnName: item_digitalObject_id_mv
      invert: false
      selection:
        - v:
            v: false
    mode: row-based
  columnName: digitalObject_id_mv
  expression: |
    grel:
    filter(
      cells['item_digitalObject_id_mv'].value.split('␟'),
      f,
      f[0] != '␣'
    )[0].split('␝')[0]
