# Facette Datenbestand
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel: 'Handschriften Einzelnachweise'
  newColumnName: filterSource
  columnInsertIndex: 1 # hinter Spalte id
