# Facette Ort
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          forEach(
            cells['subject_id_mv'].value.split('␟'),
            v,
            forNonBlank(
              v.cross('th','id')[0].cells['categorySub'].value,
              categorySub,
              if(
                categorySub == 'geographisches/ethnisches Schlagwort',
                forNonBlank(
                  forEach(
                    v.cross('th','id')[0].cells['title'].value.split(';'),
                    x,
                    x.replace('␣','').replace('ohne Ort','').replace('[u.a.]','').replace('und andere','').trim()
                  ).join('␟'),
                  z,
                  z,
                  null
                ),
                null
              ),
              null
            )
          ).join('␟'),
          x,
          x,
          null
        )
      ].uniques().join('␟'),
      x,
      forEach(
        x.split('␟'),
        v,
        with(
          if(
            v.startsWith('('),
            v.replace('(','').replace(')',''),
            if(
              v.startsWith('['),
              v.replace('[','').replace(']',''),
              v
            )
          ),
          w,
          if(
            w.startsWith('␝'),
            null,
            w
          )
        )
      ).join('␟'),
      null
    )
  newColumnName: filterLocation_mv
  columnInsertIndex: 2
