# Facette Sprache mit Typ (Übersetzung oder Original)
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      cells['language_mv'].value,
      v,
      forEach(
        v.split('␟'),
        x,
        if(
          x.length() > 3,
          x + '␝' + 'Original',
          null
        )
      ).uniques().join('␟'),
      null
    )
  newColumnName: filterLanguageType_mv
  columnInsertIndex: 2
