# Facette Ort
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          forEach(
            cells['subjectLocation_id_mv'].value.split('␟'),
            v,
            forNonBlank(
              forEach(
                v.cross('th','id')[0].cells['title'].value.split(';'),
                x,
                x.replace('␣','').replace('ohne Ort','').replace('[u.a.]','').replace('und andere','').trim()
              ).join('␟'),
              z,
              z,
              null
            )
          ).join('␟'),
          x,
          x,
          null
        )
      ].uniques().join('␟'),
      x,
      forEach(
        x.split('␟'),
        v,
        with(
          if(
            v.startsWith('('),
            v.replace('(','').replace(')',''),
            if(
              v.startsWith('['),
              v.replace('[','').replace(']',''),
              v
            )
          ),
          vv,
          with(
            if(
              vv.startsWith('␝'),
              null,
              vv
            ),
            vvv,
            if(
              vvv.find('[').length() != vvv.find(']').length(),
              vvv.replace('[','').replace(']',''),
              vvv
            )
          )
        )
      ).join('␟'),
      null
    )
  newColumnName: filterLocation_mv
  columnInsertIndex: 2
