# Filter Mehrteilig (Boolean)
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    true
  newColumnName: filterMultipart
  columnInsertIndex: 1 # hinter Spalte id