# note
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      cells['note'].value,
      x,
      x.replace('\n', '. '),
      'ohne Titel'
    )
  newColumnName: display
  columnInsertIndex: 1
