# title (dateLifespanStart[0,4]-dateLifespanEnd[0,4])
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      cells['title'].value,
      x,
      x,
      'ohne Titel'
    )
    + forNonBlank(
      forNonBlank(
        cells['dateLifespanStart'].value[0,4],
        x,
        x,
        ''
      )
      + forNonBlank(
        cells['dateLifespanEnd'].value[0,4],
        x,
        '-' + x,
        ''
      ),
      x,
      ' (' + x + ')',
      ''
    )
  newColumnName: display
  columnInsertIndex: 1
