# title (Jahresangabe aus dateLifespanStart-Jahresangabe aus dateLifespanEnd)
# Jahresangabe wird bei Personen extrahiert mit RegEx positive lookahead, weil auch Angaben v. Chr. (-0123) erlaubt sind
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      cells['title'].value,
      x,
      x,
      'ohne Titel'
    )
    + forNonBlank(
      forNonBlank(
        cells['dateLifespanStart'].value,
        x,
        x.split(/(?=-)/)[0],
        ''
      )
      + forNonBlank(
        cells['dateLifespanEnd'].value,
        x,
        '–' + x.split(/(?=-)/)[0],
        ''
      ),
      x,
      ' (' + x + ')',
      ''
    )
  newColumnName: display
  columnInsertIndex: 1
