# Dateinamenserweiterung ermitteln aus URL
- op: core/column-addition
  engineConfig:
    facets: []
  baseColumnName: hyperlink
  # String nach dem ersten ? entfernen (URL-Parameter)
  # String vor dem ersten . enfernen (erster Teil der Domain und ggf. Protokoll)
  # String vor dem letzten / entfernen
  # String vor dem letzten . entfernen
  # es verbleibt die Dateinamenserweiterung
  expression: |
    grel:
    forNonBlank(
      value.partition('?')[0].partition('.')[2].rpartition('/')[2].rpartition('.')[2],
      x,
      x,
      null
    )
  newColumnName: fileExtension
  columnInsertIndex: 2
