# Anreicherung der Wikipedia-URL aus lobid-gnd
# über separat generierten Enrichment Cache (vgl. https://github.com/opencultureconsulting/dla-opac-gnd-enrichment)
# Import dieser TSV-Dateien direkt aus GitHub Repo (vgl. scripts/main.sh)
# Hier: lobid-dewiki.tsv als OpenRefine-Projekt "lobid-dewiki"
# Spalte "key": GND-ID
# Spalte "value": Wikipedia-URL
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: gnd_id_mv
  expression: | # Es werden für alle GND-IDs alle Wikipedia-URLs ermittelt, aber zur Vereinfachung nur eine einzelne Wikipedia-URL übernommen
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          forEach(
            v.cross('lobid-dewiki','key'),
            r,
            r.cells['value'].value
          ).join('␟'),
          x,
          x,
          null
        )
      ).join('␟'),
      x,
      x.split('␟')[0],
      null
    )
  newColumnName: linkWikipedia
  columnInsertIndex: 2
