# Anreicherung der Links zu Unterschriften in Wikimedia Commons (P109) aus Wikidata
# über separat generierten Enrichment Cache (vgl. https://github.com/opencultureconsulting/dla-opac-gnd-enrichment)
# Import dieser TSV-Dateien direkt aus GitHub Repo (vgl. scripts/main.sh)
# Hier: wikidata-P109.tsv als OpenRefine-Projekt "wikidata-P109"
# Spalte "key": GND-ID
# Spalte "value": Commons Dateiname
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: linkWikidata
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          forEach(
            v.cross('wikidata-P109','key'),
            r,
            r.cells['value'].value
          ).join('␟'),
          x,
          x,
          null
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: linkCommonsSignature_file_mv
  columnInsertIndex: 2
