# Anreicherung der Links zu Wikimedia Commons aus lobid-gnd depiction und Wikidata P18
# über separat generierten Enrichment Cache (vgl. https://github.com/opencultureconsulting/dla-opac-gnd-enrichment)
# Import dieser TSV-Dateien direkt aus GitHub Repo (vgl. scripts/main.sh)
# Hier: lobid-depiction.tsv als OpenRefine-Projekt "lobid-depiction"
# Hier: wikidata-P18.tsv als OpenRefine-Projekt "wikidata-P18"
# Spalte "key": GND-ID bzw. Wikidata-ID
# Spalte "value": Commons Dateiname
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: id
  expression: |
    grel:
    forNonBlank(
      [
        forNonBlank(
          forEach(
            cells['gnd_id_mv'].value.split('␟'),
            v,
            forNonBlank(
              forEach(
                v.cross('lobid-depiction','key'),
                r,
                r.cells['value'].value
              ).join('␟'),
              x,
              x,
              null
            )
          ).join('␟'),
          x,
          x,
          null
        ),
        forNonBlank(
          forEach(
            cells['linkWikidata'].value.split('␟'),
            v,
            forNonBlank(
              forEach(
                v.cross('wikidata-P18','key'),
                r,
                r.cells['value'].value
              ).join('␟'),
              x,
              x,
              null
            )
          ).join('␟'),
          x,
          x,
          null
        )
      ].uniques().join('␟'),
      z,
      z,
      null
    )
  newColumnName: linkCommonsImage_file_mv
  columnInsertIndex: 2
