# Anreicherung der Links zu offiziellen Webseiten (P856) aus Wikidata
# über separat generierten Enrichment Cache (vgl. https://github.com/dla-marbach/dla-opac-gnd-enrichment)
# Import dieser TSV-Dateien direkt aus GitHub Repo (vgl. scripts/main.sh)
# Hier: wikidata-P856.tsv als OpenRefine-Projekt "wikidata-P856"
# Spalte "key": GND-ID
# Spalte "value": Wikipedia-URL
- op: core/column-addition
  engineConfig:
    facets: []
    mode: row-based
  baseColumnName: linkWikidata
  expression: |
    grel:
    forNonBlank(
      forEach(
        value.split('␟'),
        v,
        forNonBlank(
          forEach(
            v.cross('wikidata-P856','key'),
            r,
            r.cells['value'].value
          ).join('␟'),
          x,
          x,
          null
        )
      ).join('␟'),
      x,
      x,
      null
    )
  newColumnName: linkWikidataWebsite_mv
  columnInsertIndex: 2
